services:
  postgres:
    image: digitalcloudninja/postgresql
    platform: linux/arm64
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=ChangeMeNow!"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
volumes:
  postgres_data:
    driver: local